output:
  folder: output/table2/cifar10_guess_rnn
  target_model_count: 50
dataset:
  name: cifar10
  mnistcifar:
    num_classes: 2
model:
  arch: rnn
  rnn:
    N: 32
    H_in: 3
    H_out: 64
    scale: 0.1
    r_min: 0
    r_max: 1
    max_phase: 6.28
    embedding_size: 1
    efficient_rnn_forward_pass: False
    complex: False
    transition_matrix_parametrization: diag_real_im
    gamma_normalization: False
    official_glorot_init: False
    linear_recurrent: True
    embeddings_type: none
    guess_encoder_layer_params: False
    enable_forward_normalize: False
    num_of_rnn_layers: 1
    framework: jax
  init: "rnn"
  model_count: 5000
  model_count_times_batch_size: 10000
optimizer:
  name: guess
training:
  seed: 0
distributed:
  loss_thres: 0,10000
  num_samples: 2,16
  target_model_count_subrun: 1
  new_run: True
  tmux_id: -1
  gpu_id: "0"



