output:
  folder: output/table2/mnist_guess_rnn
  target_model_count: 175
dataset:
  name: mnist
  mnistcifar:
    num_classes: 2
model:
  arch: rnn
  rnn:
    N: 16
    H_in: 28
    H_out: 64
    embedding_size: 9
    complex: False
    diagonal: False
    linear_recurrent: False
    embeddings_type: "none"
    num_of_rnn_layers: 1
  init: "rnn"
  model_count: 20000
  model_count_times_batch_size: 160000
optimizer:
  name: guess
training:
  seed: 0
distributed:
  loss_thres: 0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65
  num_samples: 2,4,8,16,32
  target_model_count_subrun: 1