output:
  folder: output/table2/mnist_guess_rnn
  target_model_count: 50
dataset:
  name: mnist
  mnistcifar:
    num_classes: 2
model:
  arch: rnn
  rnn:
    N: 32
    H_in: 1
    H_out: 64
    scale: 0.1
    r_min: 0
    r_max: 1
    max_phase: 3.14
    embedding_size: 600
    efficient_rnn_forward_pass: False
    complex: True
    transition_matrix_parametrization: diag_stable_ring_init
    gamma_normalization: True
    official_glorot_init: False
    linear_recurrent: True
    embeddings_type: linear
    enable_forward_normalize: False
    num_of_rnn_layers: 1
    framework: jax
  init: "rnn"
  model_count: 5000
  model_count_times_batch_size: 10000
optimizer:
  name: guess
training:
  seed: 0
distributed:
  loss_thres: 0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7
  num_samples: 2,4,8,16
  target_model_count_subrun: 1
  new_run: True
  tmux_id: -1
  gpu_id: "3"



