output:
  folder: output/table2/mnist_guess_rnn
  target_model_count: 50
dataset:
  name: mnist
  mnistcifar:
    num_classes: 2
model:
  arch: rnn
  rnn:
    N: 32
    H_in: 100
    H_out: 64
    scale: 0.11
    r_min: 0
    r_max: 1
    max_phase: 6.28
    embedding_size: 10
    efficient_rnn_forward_pass: False
    complex: True
    transition_matrix_parametrization: diag_stable_ring_init
    gamma_normalization: True
    official_glorot_init: False
    linear_recurrent: True
    embeddings_type: pix_to_vec_to_vec
    enable_forward_normalize: False
    num_of_rnn_layers: 1
  init: "rnn"
  model_count: 5000
  model_count_times_batch_size: 40000
optimizer:
  name: guess
training:
  seed: 0
distributed:
  loss_thres: 0,1000000
  num_samples: 2,4,8,16
  target_model_count_subrun: 1
  new_run: True
  tmux_id: -1



